name: Node.js CI - with cache

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name = 'push'
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Restore Cache
      id: cache
      uses: actions/cache@v4.2.3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'
    - name: run build
      run: npm ci
    - run: npm run build --if-present    
    - name: Save Cache    
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache@v4.2.3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: packt-app
        path: dist/
        retention-days: 1
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4.3.0
      with:
        name: packt-app
        path: download-content
